export const CHAT_INFO_REQUEST = "CHAT_INFO_REQUEST";
export const CHAT_INFO_SUCCESS = "CHAT_INFO_SUCCESS";
export const CHAT_INFO_FAIL = "CHAT_INFO_FAIL";
export const CHAT_INFO_RESET = "CHAT_INFO_RESET";

export const CHAT_COMMENT_QUANTITY_REQUEST = "CHAT_COMMENT_QUANTITY_REQUEST";
export const CHAT_COMMENT_QUANTITY_SUCCESS = "CHAT_COMMENT_QUANTITY_SUCCESS";
export const CHAT_COMMENT_QUANTITY_FAIL = "CHAT_COMMENT_QUANTITY_FAIL";
export const CHAT_COMMENT_QUANTITY_RESET = "CHAT_COMMENT_QUANTITY_RESET";

export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";
export const CHAT_LIST_RESET = "CHAT_LIST_RESET";

export const CHAT_COMMENT_REQUEST = "CHAT_COMMENT_REQUEST";
export const CHAT_COMMENT_SUCCESS = "CHAT_COMMENT_SUCCESS";
export const CHAT_COMMENT_FAIL = "CHAT_COMMENT_FAIL";
export const CHAT_COMMENT_RESET = "CHAT_COMMENT_RESET";