# Generated by Django 4.2.2 on 2023-06-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('image', models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('positive', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('negative', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('neutral', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('positive', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('negative', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('neutral', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/user-default.png', null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
