# Generated by Django 4.2.2 on 2023-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_negative_alter_comment_neutral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='positive',
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
