# Generated by Django 4.2.2 on 2023-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_comment_negative_remove_comment_neutral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
